<?php
namespace FileBank\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AltName
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class File extends EntityRepository
{
    public function __construct()
    {
        exit();
    }
    
}
